### ISSUE TITLE
metrics_format doesn't honor field variable names

### ISSUE THREAD

**Issue by blysik** [logstash-plugins/logstash-output-graphite#15]
```
metrics_format => "team.infra.poller.%{host}.*"
```

Results in a actual directory on the graphite filesystem of %{host}.  What's expected is the value of that field.

**Comment by andrewvc** [comment]
Mmmm, this should be a simple matter of adding a call to sprintf to that field

**Comment by andrewvc** [comment]
Released in version 1.0.2

Thanks for filing the report @blysik !

**Comment by blysik** [comment]
Tested and confirmed works.  Thanks!

**Comment by andrewvc** [comment]
@blysik I'm really interested in what it is you're putting together. Is there any chance you'll be putting this info up as a blog post? If so, I'd love to reshare it both on my network and with the logstash team!
