### ISSUE TITLE
pushing to graphite old apache logs 

### ISSUE THREAD

**Issue by xinity** [logstash-plugins/logstash-output-graphite#9]
hy,

been knocking my head on how to push to graphite old apache logs (response, bytes).
here is my test config:
input {
  file {
    path => "/mnt/apache2/mywebhost-access.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"  
  }
}
filter {
    grok {
    match => { "message" => "%{COMBINEDAPACHELOG}" }
    }
mutate {
      add_field => [ "websrc", "%{referrer}" ]
    }
mutate {
      split => ["websrc", "/"]
    }
mutate {
      replace => [ "websrc", "%{[websrc][2]}" ]
    }
date {
    match => [ "timestamp" , "dd/MMM/yyyy:HH:mm:ss Z" ]
  }
}
output {
graphite {
    host => 'graphite'
    port => 2003
    metrics => ['logstash.event','1', 'hosts.%{websrc}.apache.%{response}', '%{bytes}']
  }
stdout { 
codec => rubydebug
}
    file {
      path => "/mnt/apache2/graphitedebug.log"
       }
}

i can see carbon writing data while putting carbon-cache in debug mode:
19/02/2015 07:58:48 :: [creates] new metric hosts.mywebhost.apache.200 matched schema default
19/02/2015 07:58:48 :: [creates] creating database file /var/lib/graphite/storage/whisper/hosts/mywebhost/apache/200.wsp (archive=[(10, 69120), (60, 44640), (60
0, 52560), (3600, 43800)] xff=0.5 agg=average)

but it seems the timestamp used to write the data , in my system timestamp, and not the timestamp from the log files.

did i miss something ?

**Comment by jsvd** [comment]
@xinity were you able to understand what happened?

**Comment by xinity** [comment]
@jsvd nop by the time i've switched to another project as this was an R&D one :(

**Comment by jsvd** [comment]
@xinity thanks for reporting it and sorry for ignoring it :( without more information I won't be able to debug this, so I'll close the issue and reopen if someone else hits the same problem in the future.
